# Generated by Django 3.2.14 on 2022-11-21 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalltask',
            name='smalltask_id',
            field=models.UUIDField(default=uuid.UUID('3655fc39-3b9f-42bb-8cc1-4ebd078bb69d'), primary_key=True, serialize=False, verbose_name='小タスクID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('3aae48ab-5a57-4047-b2f8-9498452993ae'), primary_key=True, serialize=False, verbose_name='タスクID'),
        ),
    ]
