# Generated by Django 3.2.14 on 2022-11-21 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0002_auto_20221121_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalltask',
            name='smalltask_id',
            field=models.UUIDField(default=uuid.UUID('24201695-5afb-40d4-9290-b992a9925411'), primary_key=True, serialize=False, verbose_name='小タスクID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('b2904c6a-8ad2-4361-9874-c1ec4fcd246e'), primary_key=True, serialize=False, verbose_name='タスクID'),
        ),
    ]
