# Generated by Django 3.2.14 on 2022-11-21 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0003_auto_20221121_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalltask',
            name='smalltask_id',
            field=models.UUIDField(default=uuid.UUID('d6ef9d0d-6687-4ce9-b7cd-a44c87fd0c73'), primary_key=True, serialize=False, verbose_name='小タスクID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('5a8cb8c3-9108-4502-a4f0-1bc45cdd61a5'), primary_key=True, serialize=False, verbose_name='タスクID'),
        ),
    ]
