# Generated by Django 3.2.14 on 2022-11-21 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0004_auto_20221121_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalltask',
            name='smalltask_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='小タスクID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='タスクID'),
        ),
    ]
