# Generated by Django 3.2.14 on 2022-11-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0005_auto_20221121_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='drf_test_app.customuser'),
            preserve_default=False,
        ),
    ]
