# Generated by Django 3.2.14 on 2022-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0006_task_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Eメールアドレス'),
        ),
    ]
