# Generated by Django 3.2.14 on 2023-01-09 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
