# Generated by Django 3.2.14 on 2023-01-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0008_alter_task_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=255, verbose_name='モチベーション')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drf_test_app.task')),
            ],
        ),
    ]
